package com.design.learn.ddos;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;

public class MongoDbTest {

//    public static void main(String[] args) {
//        //利用线程池创建1000个线程
//       ExecutorService es = Executors.newFixedThreadPool(500);
//        TestMongoDb ddos = new TestMongoDb();
//        Thread thread = new Thread(ddos);
//        thread.start();
//        for (int i = 0; i < 500; i++) {
//            es.execute(thread);
//        }
//
//       // es.shutdown();
//    }


    public static void main(String[] args){
        String ss = "{\n" +
                "    \"returnState\":1,\n" +
                "    \"returnData\":{\n" +
                "        \"goods_member_level_info\":{\n" +
                "            \"seller_id\":\"50331648\",\n" +
                "            \"shop_id\":\"1\",\n" +
                "            \"level_seller_id\":\"50331648\",\n" +
                "            \"level_id\":\"2\",\n" +
                "            \"goods_unicode\":\"216172782113784577\",\n" +
                "            \"agent_seller_id\":\"50331648\",\n" +
                "            \"member_type\":\"3\",\n" +
                "            \"discounts_type\":\"2\",\n" +
                "            \"discounts\":\"100\",\n" +
                "            \"is_member_product\":\"0\",\n" +
                "            \"description\":\"\",\n" +
                "            \"create_uid\":\"216172782113783809\",\n" +
                "            \"create_time\":\"2020-07-21 16:59:09\",\n" +
                "            \"update_uid\":\"216172782113783809\",\n" +
                "            \"update_time\":\"2020-07-21 16:59:09\",\n" +
                "            \"is_visible\":\"0\"\n" +
                "        },\n" +
                "        \"shop_member_info\":{\n" +
                "            \"flag\":\"1\",\n" +
                "            \"level_id\":\"2\",\n" +
                "            \"open_id\":\"ouhWb5ZiP1y7n0xyDIO_GJTJJaW8\",\n" +
                "            \"fav_status\":\"0\",\n" +
                "            \"mobile_no\":\"18707750316\",\n" +
                "            \"user_id\":\"13907678599273512964\",\n" +
                "            \"user_name\":\"罗晓丹\",\n" +
                "            \"create_time\":\"2020-06-10 14:18:26\",\n" +
                "            \"bonus_seller_id\":\"33554432\"\n" +
                "        },\n" +
                "        \"theme_data\":{\n" +
                "            \"bonus_mybonus_01\":\"31\",\n" +
                "            \"home_goods_cate_01\":[\n" +
                "\n" +
                "            ],\n" +
                "            \"home_navi_01\":[\n" +
                "                {\n" +
                "                    \"category_id\":\"67371008\",\n" +
                "                    \"level\":\"2\",\n" +
                "                    \"cate_name\":\"艺术品\",\n" +
                "                    \"link_config\":\"\",\n" +
                "                    \"link_type\":\"4\",\n" +
                "                    \"show_type\":\"0\",\n" +
                "                    \"cover_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/c72fa48e55594ae54e7115ac3fc970cd.png\",\n" +
                "                    \"is_localed\":\"0\",\n" +
                "                    \"sort\":\"1\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"category_id\":\"67174400\",\n" +
                "                    \"level\":\"2\",\n" +
                "                    \"cate_name\":\"新鲜水果\",\n" +
                "                    \"link_config\":\"id=33554432&amp;code=144115188075857408\",\n" +
                "                    \"link_type\":\"4\",\n" +
                "                    \"show_type\":\"3\",\n" +
                "                    \"cover_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/27de9b48baf20ba0a327338c58d508ab.png\",\n" +
                "                    \"is_localed\":\"0\",\n" +
                "                    \"sort\":\"99\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"category_id\":\"67436544\",\n" +
                "                    \"level\":\"2\",\n" +
                "                    \"cate_name\":\"每日上新\",\n" +
                "                    \"link_config\":\"\",\n" +
                "                    \"link_type\":\"0\",\n" +
                "                    \"show_type\":\"0\",\n" +
                "                    \"cover_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/a73f33abb36f6a78224626878656edbd.png\",\n" +
                "                    \"is_localed\":\"0\",\n" +
                "                    \"sort\":\"99\"\n" +
                "                }\n" +
                "            ],\n" +
                "            \"home_advertise_01\":{\n" +
                "                \"HA\":[\n" +
                "                    {\n" +
                "                        \"is_default\":\"0\",\n" +
                "                        \"size_tag\":\"HA\",\n" +
                "                        \"media_type\":\"2\",\n" +
                "                        \"image_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/f99d3a90cab32dcede495f7d5e3832bb.jpg\",\n" +
                "                        \"href\":\"id=33554432&amp;code=144115188075856128&amp;intype=1\",\n" +
                "                        \"site_advertise_id\":\"5\",\n" +
                "                        \"seller_id\":\"33554432\",\n" +
                "                        \"seller_name\":\"尽猎积分商城\",\n" +
                "                        \"goods_name\":\"短信\",\n" +
                "                        \"jump_type\":2\n" +
                "                    },\n" +
                "                    {\n" +
                "                        \"is_default\":\"0\",\n" +
                "                        \"size_tag\":\"HA\",\n" +
                "                        \"media_type\":\"2\",\n" +
                "                        \"image_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/841148997cc5361705c7feac22190d43.jpg\",\n" +
                "                        \"href\":\"id=33554432&amp;code=144115188075856128&amp;intype=1\",\n" +
                "                        \"site_advertise_id\":\"6\",\n" +
                "                        \"seller_id\":\"33554432\",\n" +
                "                        \"seller_name\":\"尽猎积分商城\",\n" +
                "                        \"goods_name\":\"短信\",\n" +
                "                        \"jump_type\":2\n" +
                "                    },\n" +
                "                    {\n" +
                "                        \"is_default\":\"0\",\n" +
                "                        \"size_tag\":\"HA\",\n" +
                "                        \"media_type\":\"2\",\n" +
                "                        \"image_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/5ab88110ed74ae63467bf23ea7e3720a.png\",\n" +
                "                        \"href\":\"id=33554432&amp;code=144115188075856128&amp;intype=1\",\n" +
                "                        \"site_advertise_id\":\"7\",\n" +
                "                        \"seller_id\":\"33554432\",\n" +
                "                        \"seller_name\":\"尽猎积分商城\",\n" +
                "                        \"goods_name\":\"短信\",\n" +
                "                        \"jump_type\":2\n" +
                "                    },\n" +
                "                    {\n" +
                "                        \"is_default\":\"0\",\n" +
                "                        \"size_tag\":\"HA\",\n" +
                "                        \"media_type\":\"2\",\n" +
                "                        \"image_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/60e0fb82de6e06b714720faf2b44c482.png\",\n" +
                "                        \"href\":\"id=33554432&amp;code=144115188075856128&amp;intype=1\",\n" +
                "                        \"site_advertise_id\":\"8\",\n" +
                "                        \"seller_id\":\"33554432\",\n" +
                "                        \"seller_name\":\"尽猎积分商城\",\n" +
                "                        \"goods_name\":\"短信\",\n" +
                "                        \"jump_type\":2\n" +
                "                    }\n" +
                "                ]\n" +
                "            },\n" +
                "            \"home_navi_02\":[\n" +
                "                {\n" +
                "                    \"childnodes\":[\n" +
                "                        {\n" +
                "                            \"category_id\":\"17039360\",\n" +
                "                            \"level\":\"2\",\n" +
                "                            \"cate_name\":\"本地栏目\",\n" +
                "                            \"link_config\":\"\",\n" +
                "                            \"link_type\":null,\n" +
                "                            \"show_type\":\"0\",\n" +
                "                            \"cover_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/638ba7faaabf423dbcf589973aadf261.jpg\",\n" +
                "                            \"is_localed\":\"1\",\n" +
                "                            \"sort\":\"1\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"category_id\":\"17104896\",\n" +
                "                            \"level\":\"2\",\n" +
                "                            \"cate_name\":\"艺术品\",\n" +
                "                            \"link_config\":\"\",\n" +
                "                            \"link_type\":null,\n" +
                "                            \"show_type\":\"0\",\n" +
                "                            \"cover_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/3cb9512f069165e04df9b863b6f498e1.png\",\n" +
                "                            \"is_localed\":\"0\",\n" +
                "                            \"sort\":\"2\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"category_id\":\"16842752\",\n" +
                "                            \"level\":\"2\",\n" +
                "                            \"cate_name\":\"新鲜水果\",\n" +
                "                            \"link_config\":\"\",\n" +
                "                            \"link_type\":null,\n" +
                "                            \"show_type\":\"18\",\n" +
                "                            \"cover_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/006ae2d3d79401c5999c4f0899483ac1.png\",\n" +
                "                            \"is_localed\":\"0\",\n" +
                "                            \"sort\":\"3\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"category_id\":\"16908288\",\n" +
                "                            \"level\":\"2\",\n" +
                "                            \"cate_name\":\"美肤美妆\",\n" +
                "                            \"link_config\":\"\",\n" +
                "                            \"link_type\":null,\n" +
                "                            \"show_type\":\"18\",\n" +
                "                            \"cover_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/270496c5e90d85b918860e8ab288e0fe.png\",\n" +
                "                            \"is_localed\":\"1\",\n" +
                "                            \"sort\":\"4\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"category_id\":\"16973824\",\n" +
                "                            \"level\":\"2\",\n" +
                "                            \"cate_name\":\"爆款沙发\",\n" +
                "                            \"link_config\":\"\",\n" +
                "                            \"link_type\":null,\n" +
                "                            \"show_type\":\"0\",\n" +
                "                            \"cover_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/8d25b7f2a63c7915cc167ed976b8ddbb.png\",\n" +
                "                            \"is_localed\":\"0\",\n" +
                "                            \"sort\":\"5\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                }\n" +
                "            ],\n" +
                "            \"home_goods_cate_02\":[\n" +
                "                {\n" +
                "                    \"category_id\":\"33554432\",\n" +
                "                    \"level\":\"1\",\n" +
                "                    \"cate_name\":\"精选热卖\",\n" +
                "                    \"link_config\":\"\",\n" +
                "                    \"link_type\":\"0\",\n" +
                "                    \"show_type\":\"3\",\n" +
                "                    \"cover_url\":\"\",\n" +
                "                    \"is_localed\":\"0\",\n" +
                "                    \"sort\":\"99\",\n" +
                "                    \"goodslist\":[\n" +
                "                        {\n" +
                "                            \"seller_id\":\"50331654\",\n" +
                "                            \"goods_unicode\":\"216172807883588096\",\n" +
                "                            \"goods_name\":\"51关山月《秋溪放筏图》水墨画国画框艺术摆件创意家居客厅电视柜玄关装饰办公室工艺品1\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/606b379ad424fe6953e98d668a3d84e3.png\",\n" +
                "                            \"sale_price\":\"1.00\",\n" +
                "                            \"member_price\":\"1.00\",\n" +
                "                            \"bonus_sale\":\"50\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"33554432\",\n" +
                "                            \"goods_unicode\":\"144115188075856128\",\n" +
                "                            \"goods_name\":\"短信\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/b93d84bea9a9d9b4f590f4930978378b.jpg\",\n" +
                "                            \"sale_price\":\"0.00\",\n" +
                "                            \"member_price\":\"0.00\",\n" +
                "                            \"bonus_sale\":\"200\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"3238264833\",\n" +
                "                            \"goods_unicode\":\"13908241553521901824\",\n" +
                "                            \"goods_name\":\"(钱)棉凉鞋\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/74a0946722c1aef5311a1e75bda0ba3f.png\",\n" +
                "                            \"sale_price\":\"0.01\",\n" +
                "                            \"member_price\":\"0.01\",\n" +
                "                            \"bonus_sale\":\"100\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"33554432\",\n" +
                "                            \"goods_unicode\":\"144115188075856384\",\n" +
                "                            \"goods_name\":\"积分商城的鞋子\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/b9c1824812ea011a7cc5ba67f1a44b71.jpg\",\n" +
                "                            \"sale_price\":\"0.00\",\n" +
                "                            \"member_price\":\"0.00\",\n" +
                "                            \"bonus_sale\":\"1\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                }\n" +
                "            ],\n" +
                "            \"home_goods_cate_03\":[\n" +
                "                {\n" +
                "                    \"category_id\":\"50331648\",\n" +
                "                    \"level\":\"1\",\n" +
                "                    \"cate_name\":\"消分专区\",\n" +
                "                    \"link_config\":\"\",\n" +
                "                    \"link_type\":\"0\",\n" +
                "                    \"show_type\":\"3\",\n" +
                "                    \"cover_url\":\"\",\n" +
                "                    \"is_localed\":\"0\",\n" +
                "                    \"sort\":\"99\",\n" +
                "                    \"goodslist\":[\n" +
                "                        {\n" +
                "                            \"seller_id\":\"50331656\",\n" +
                "                            \"goods_unicode\":\"216172816473527808\",\n" +
                "                            \"goods_name\":\"（玉兔）积木玩具儿童玩具拼装模型军事积木兼容积木益智玩具6-8岁生日礼物 【礼盒】8合1战火先锋 502+片+2人偶\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/73a4f1f1eb462ec0f10e7b6381bebb2d.jpg\",\n" +
                "                            \"sale_price\":\"0.01\",\n" +
                "                            \"member_price\":\"0.01\",\n" +
                "                            \"bonus_sale\":\"1\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                }\n" +
                "            ],\n" +
                "            \"home_goods_cate_04\":[\n" +
                "                {\n" +
                "                    \"category_id\":\"67108864\",\n" +
                "                    \"level\":\"1\",\n" +
                "                    \"cate_name\":\"自定义商品栏目\",\n" +
                "                    \"link_config\":\"\",\n" +
                "                    \"link_type\":\"0\",\n" +
                "                    \"show_type\":\"13\",\n" +
                "                    \"cover_url\":\"\",\n" +
                "                    \"is_localed\":\"0\",\n" +
                "                    \"sort\":\"99\",\n" +
                "                    \"goodslist\":[\n" +
                "\n" +
                "                    ],\n" +
                "                    \"childnodes\":[\n" +
                "                        {\n" +
                "                            \"category_id\":\"67371008\",\n" +
                "                            \"level\":\"2\",\n" +
                "                            \"cate_name\":\"艺术品\",\n" +
                "                            \"link_config\":\"\",\n" +
                "                            \"link_type\":\"4\",\n" +
                "                            \"show_type\":\"0\",\n" +
                "                            \"cover_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/c72fa48e55594ae54e7115ac3fc970cd.png\",\n" +
                "                            \"is_localed\":\"0\",\n" +
                "                            \"sort\":\"1\",\n" +
                "                            \"goodslist\":[\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331654\",\n" +
                "                                    \"goods_unicode\":\"216172807883588096\",\n" +
                "                                    \"goods_name\":\"51关山月《秋溪放筏图》水墨画国画框艺术摆件创意家居客厅电视柜玄关装饰办公室工艺品1\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/606b379ad424fe6953e98d668a3d84e3.png\",\n" +
                "                                    \"sale_price\":\"1.00\",\n" +
                "                                    \"member_price\":\"1.00\",\n" +
                "                                    \"bonus_sale\":\"50\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"33554432\",\n" +
                "                                    \"goods_unicode\":\"144115188075856128\",\n" +
                "                                    \"goods_name\":\"短信\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/b93d84bea9a9d9b4f590f4930978378b.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"200\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"33554432\",\n" +
                "                                    \"goods_unicode\":\"144115188075856384\",\n" +
                "                                    \"goods_name\":\"积分商城的鞋子\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/b9c1824812ea011a7cc5ba67f1a44b71.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"1\"\n" +
                "                                }\n" +
                "                            ]\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"category_id\":\"67174400\",\n" +
                "                            \"level\":\"2\",\n" +
                "                            \"cate_name\":\"新鲜水果\",\n" +
                "                            \"link_config\":\"id=33554432&amp;code=144115188075857408\",\n" +
                "                            \"link_type\":\"4\",\n" +
                "                            \"show_type\":\"3\",\n" +
                "                            \"cover_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/27de9b48baf20ba0a327338c58d508ab.png\",\n" +
                "                            \"is_localed\":\"0\",\n" +
                "                            \"sort\":\"99\",\n" +
                "                            \"goodslist\":[\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"33554432\",\n" +
                "                                    \"goods_unicode\":\"144115188075856128\",\n" +
                "                                    \"goods_name\":\"短信\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/b93d84bea9a9d9b4f590f4930978378b.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"200\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"33554432\",\n" +
                "                                    \"goods_unicode\":\"144115188075857408\",\n" +
                "                                    \"goods_name\":\"积分商城的宝石\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/265e4a62941615d50de9a5f8809cc790.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"500\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331654\",\n" +
                "                                    \"goods_unicode\":\"216172807883588096\",\n" +
                "                                    \"goods_name\":\"51关山月《秋溪放筏图》水墨画国画框艺术摆件创意家居客厅电视柜玄关装饰办公室工艺品1\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/606b379ad424fe6953e98d668a3d84e3.png\",\n" +
                "                                    \"sale_price\":\"1.00\",\n" +
                "                                    \"member_price\":\"1.00\",\n" +
                "                                    \"bonus_sale\":\"50\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"33554432\",\n" +
                "                                    \"goods_unicode\":\"144115188075856640\",\n" +
                "                                    \"goods_name\":\"积分商城的短袖\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/f7ede98ddba026c4455ed0b7da351079.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"100\"\n" +
                "                                }\n" +
                "                            ]\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"category_id\":\"67436544\",\n" +
                "                            \"level\":\"2\",\n" +
                "                            \"cate_name\":\"每日上新\",\n" +
                "                            \"link_config\":\"\",\n" +
                "                            \"link_type\":\"0\",\n" +
                "                            \"show_type\":\"0\",\n" +
                "                            \"cover_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/a73f33abb36f6a78224626878656edbd.png\",\n" +
                "                            \"is_localed\":\"0\",\n" +
                "                            \"sort\":\"99\",\n" +
                "                            \"goodslist\":[\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331654\",\n" +
                "                                    \"goods_unicode\":\"216172807883588096\",\n" +
                "                                    \"goods_name\":\"51关山月《秋溪放筏图》水墨画国画框艺术摆件创意家居客厅电视柜玄关装饰办公室工艺品1\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/606b379ad424fe6953e98d668a3d84e3.png\",\n" +
                "                                    \"sale_price\":\"1.00\",\n" +
                "                                    \"member_price\":\"1.00\",\n" +
                "                                    \"bonus_sale\":\"50\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331656\",\n" +
                "                                    \"goods_unicode\":\"216172816473527808\",\n" +
                "                                    \"goods_name\":\"（玉兔）积木玩具儿童玩具拼装模型军事积木兼容积木益智玩具6-8岁生日礼物 【礼盒】8合1战火先锋 502+片+2人偶\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/73a4f1f1eb462ec0f10e7b6381bebb2d.jpg\",\n" +
                "                                    \"sale_price\":\"0.01\",\n" +
                "                                    \"member_price\":\"0.01\",\n" +
                "                                    \"bonus_sale\":\"1\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"33554432\",\n" +
                "                                    \"goods_unicode\":\"144115188075857408\",\n" +
                "                                    \"goods_name\":\"积分商城的宝石\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/265e4a62941615d50de9a5f8809cc790.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"500\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331653\",\n" +
                "                                    \"goods_unicode\":\"216172803588621568\",\n" +
                "                                    \"goods_name\":\"（亥猪）发簪\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/e495d9ebef39ee8dec59533252968399.png\",\n" +
                "                                    \"sale_price\":\"2.00\",\n" +
                "                                    \"member_price\":\"2.00\",\n" +
                "                                    \"bonus_sale\":\"50\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"33554432\",\n" +
                "                                    \"goods_unicode\":\"144115188075857664\",\n" +
                "                                    \"goods_name\":\"积分商城的电脑\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/18dd2304f3e3efefb3b9f8b9e49a59ac.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"5000\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331654\",\n" +
                "                                    \"goods_unicode\":\"216172807883587840\",\n" +
                "                                    \"goods_name\":\"51霸王龙模型玩具\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/0fa080a5c80b3325044cc62cba766b05.png\",\n" +
                "                                    \"sale_price\":\"1.00\",\n" +
                "                                    \"member_price\":\"1.00\",\n" +
                "                                    \"bonus_sale\":\"1\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"33554432\",\n" +
                "                                    \"goods_unicode\":\"144115188075857920\",\n" +
                "                                    \"goods_name\":\"积分商城的平板包\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/640052639cfc94dd167beba85b99a694.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"50\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331648\",\n" +
                "                                    \"goods_unicode\":\"216172782113784576\",\n" +
                "                                    \"goods_name\":\"布鞋\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/d1dbebc27065982b6c8799c4edbe8980.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"2\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331654\",\n" +
                "                                    \"goods_unicode\":\"216172807883591424\",\n" +
                "                                    \"goods_name\":\"(51)测试商品描述\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/f290551acc50b050411966927a4369d5.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"200\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331649\",\n" +
                "                                    \"goods_unicode\":\"216172786408752128\",\n" +
                "                                    \"goods_name\":\"（花果）三角龙模型仿真玩具\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/a9b8107e6a98306bed6305e2b654c54b.png\",\n" +
                "                                    \"sale_price\":\"2.00\",\n" +
                "                                    \"member_price\":\"2.00\",\n" +
                "                                    \"bonus_sale\":\"30\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331655\",\n" +
                "                                    \"goods_unicode\":\"216172812178555392\",\n" +
                "                                    \"goods_name\":\"（黄）测试111\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/1929267ae6d379b2772ad1c3354fd8c7.jpg\",\n" +
                "                                    \"sale_price\":\"0.01\",\n" +
                "                                    \"member_price\":\"0.01\",\n" +
                "                                    \"bonus_sale\":\"1\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331649\",\n" +
                "                                    \"goods_unicode\":\"216172786408753920\",\n" +
                "                                    \"goods_name\":\"（花果）短袖（可销售）\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/566d52b3dbb34fbe782055f06c253583.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"1\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"33554432\",\n" +
                "                                    \"goods_unicode\":\"144115188075856128\",\n" +
                "                                    \"goods_name\":\"短信\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/b93d84bea9a9d9b4f590f4930978378b.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"200\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331649\",\n" +
                "                                    \"goods_unicode\":\"216172786408754944\",\n" +
                "                                    \"goods_name\":\"（花果）可体验和可体验不外送\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/003f87ec1a8f5e7a391680e152bdbdab.jpg\",\n" +
                "                                    \"sale_price\":\"1.00\",\n" +
                "                                    \"member_price\":\"1.00\",\n" +
                "                                    \"bonus_sale\":\"50\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"3238133761\",\n" +
                "                                    \"goods_unicode\":\"13907678603568480768\",\n" +
                "                                    \"goods_name\":\"丝袜\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/a296802dde63073a69e735138cc58d6b.png\",\n" +
                "                                    \"sale_price\":\"1.00\",\n" +
                "                                    \"member_price\":\"1.00\",\n" +
                "                                    \"bonus_sale\":\"30\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"33554432\",\n" +
                "                                    \"goods_unicode\":\"144115188075856640\",\n" +
                "                                    \"goods_name\":\"积分商城的短袖\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/f7ede98ddba026c4455ed0b7da351079.jpg\",\n" +
                "                                    \"sale_price\":\"0.00\",\n" +
                "                                    \"member_price\":\"0.00\",\n" +
                "                                    \"bonus_sale\":\"100\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"50331651\",\n" +
                "                                    \"goods_unicode\":\"216172794998686720\",\n" +
                "                                    \"goods_name\":\"（怀杰）测试商品1\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/f41bfc0eb323cd4b86d1149d7fd63a42.jpg\",\n" +
                "                                    \"sale_price\":\"1.00\",\n" +
                "                                    \"member_price\":\"1.00\",\n" +
                "                                    \"bonus_sale\":\"100\"\n" +
                "                                },\n" +
                "                                {\n" +
                "                                    \"seller_id\":\"3238264833\",\n" +
                "                                    \"goods_unicode\":\"13908241553521901824\",\n" +
                "                                    \"goods_name\":\"(钱)棉凉鞋\",\n" +
                "                                    \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/74a0946722c1aef5311a1e75bda0ba3f.png\",\n" +
                "                                    \"sale_price\":\"0.01\",\n" +
                "                                    \"member_price\":\"0.01\",\n" +
                "                                    \"bonus_sale\":\"100\"\n" +
                "                                }\n" +
                "                            ]\n" +
                "                        }\n" +
                "                    ]\n" +
                "                }\n" +
                "            ],\n" +
                "            \"home_goods_cate_05\":[\n" +
                "                {\n" +
                "                    \"category_id\":\"83886080\",\n" +
                "                    \"level\":\"1\",\n" +
                "                    \"cate_name\":\"猜你喜欢\",\n" +
                "                    \"link_config\":\"\",\n" +
                "                    \"link_type\":\"0\",\n" +
                "                    \"show_type\":\"3\",\n" +
                "                    \"cover_url\":\"\",\n" +
                "                    \"is_localed\":\"0\",\n" +
                "                    \"sort\":\"99\",\n" +
                "                    \"goodslist\":[\n" +
                "                        {\n" +
                "                            \"seller_id\":\"50331656\",\n" +
                "                            \"goods_unicode\":\"216172816473527808\",\n" +
                "                            \"goods_name\":\"（玉兔）积木玩具儿童玩具拼装模型军事积木兼容积木益智玩具6-8岁生日礼物 【礼盒】8合1战火先锋 502+片+2人偶\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/73a4f1f1eb462ec0f10e7b6381bebb2d.jpg\",\n" +
                "                            \"sale_price\":\"0.01\",\n" +
                "                            \"member_price\":\"0.01\",\n" +
                "                            \"bonus_sale\":\"1\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"50331648\",\n" +
                "                            \"goods_unicode\":\"216172782113784576\",\n" +
                "                            \"goods_name\":\"布鞋\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/d1dbebc27065982b6c8799c4edbe8980.jpg\",\n" +
                "                            \"sale_price\":\"0.00\",\n" +
                "                            \"member_price\":\"0.00\",\n" +
                "                            \"bonus_sale\":\"2\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"50331649\",\n" +
                "                            \"goods_unicode\":\"216172786408752128\",\n" +
                "                            \"goods_name\":\"（花果）三角龙模型仿真玩具\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/a9b8107e6a98306bed6305e2b654c54b.png\",\n" +
                "                            \"sale_price\":\"2.00\",\n" +
                "                            \"member_price\":\"2.00\",\n" +
                "                            \"bonus_sale\":\"30\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"50331651\",\n" +
                "                            \"goods_unicode\":\"216172794998686720\",\n" +
                "                            \"goods_name\":\"（怀杰）测试商品1\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/f41bfc0eb323cd4b86d1149d7fd63a42.jpg\",\n" +
                "                            \"sale_price\":\"1.00\",\n" +
                "                            \"member_price\":\"1.00\",\n" +
                "                            \"bonus_sale\":\"100\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"50331654\",\n" +
                "                            \"goods_unicode\":\"216172807883588096\",\n" +
                "                            \"goods_name\":\"51关山月《秋溪放筏图》水墨画国画框艺术摆件创意家居客厅电视柜玄关装饰办公室工艺品1\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/606b379ad424fe6953e98d668a3d84e3.png\",\n" +
                "                            \"sale_price\":\"1.00\",\n" +
                "                            \"member_price\":\"1.00\",\n" +
                "                            \"bonus_sale\":\"50\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"50331655\",\n" +
                "                            \"goods_unicode\":\"216172812178555392\",\n" +
                "                            \"goods_name\":\"（黄）测试111\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/1929267ae6d379b2772ad1c3354fd8c7.jpg\",\n" +
                "                            \"sale_price\":\"0.01\",\n" +
                "                            \"member_price\":\"0.01\",\n" +
                "                            \"bonus_sale\":\"1\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"33554432\",\n" +
                "                            \"goods_unicode\":\"144115188075856128\",\n" +
                "                            \"goods_name\":\"短信\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/b93d84bea9a9d9b4f590f4930978378b.jpg\",\n" +
                "                            \"sale_price\":\"0.00\",\n" +
                "                            \"member_price\":\"0.00\",\n" +
                "                            \"bonus_sale\":\"200\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"3238133761\",\n" +
                "                            \"goods_unicode\":\"13907678603568480768\",\n" +
                "                            \"goods_name\":\"丝袜\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/a296802dde63073a69e735138cc58d6b.png\",\n" +
                "                            \"sale_price\":\"1.00\",\n" +
                "                            \"member_price\":\"1.00\",\n" +
                "                            \"bonus_sale\":\"30\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"33554432\",\n" +
                "                            \"goods_unicode\":\"144115188075856640\",\n" +
                "                            \"goods_name\":\"积分商城的短袖\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/f7ede98ddba026c4455ed0b7da351079.jpg\",\n" +
                "                            \"sale_price\":\"0.00\",\n" +
                "                            \"member_price\":\"0.00\",\n" +
                "                            \"bonus_sale\":\"100\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"seller_id\":\"3238264833\",\n" +
                "                            \"goods_unicode\":\"13908241553521901824\",\n" +
                "                            \"goods_name\":\"(钱)棉凉鞋\",\n" +
                "                            \"img_url\":\"https://kinlie-xhz.oss-cn-hangzhou.aliyuncs.com/other/74a0946722c1aef5311a1e75bda0ba3f.png\",\n" +
                "                            \"sale_price\":\"0.01\",\n" +
                "                            \"member_price\":\"0.01\",\n" +
                "                            \"bonus_sale\":\"100\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                }\n" +
                "            ]\n" +
                "        }\n" +
                "    }\n" +
                "}";

        JSONObject dataObj= JSON.parseObject(ss);
        JSONObject returnData = dataObj.getJSONObject("returnData");
        JSONObject themeData = returnData.getJSONObject("theme_data");
        JSONArray categoryData = themeData.getJSONArray("home_goods_cate_02");
        System.out.println(categoryData);
        JSONObject categoryDataToJson =  categoryData.getJSONObject(0);
        JSONArray goodsList = categoryDataToJson.getJSONArray("goodslist");
        System.out.println(goodsList);
        JSONObject goods = goodsList.getJSONObject(0);
        String goodsUnicode = goods.getString("goods_unicode");
        System.out.println(goodsUnicode);

    }
}

